Repository Igire-Rwanda/Transport-Tech-Solution-fn, pull requests merged in 2023-06, with the labels that each got.

#6 185285091 Ft navigation
  src/pages/navigation/NavigationBar.css
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#4 #185285073 admin dashboard to control all the activities
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/component/routes/index.jsx
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/constants/index.css
  src/constants/index.jsx
  src/index.css
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
Labels: Ready to merge

#3 #185285068 driver dashboard
  Destination.js
  Driver.js
  src/App.css
  src/App.jsx
  src/component/Side/driveSidebar.css
  src/component/Side/driveSidebar.jsx
  src/component/routes/index.jsx
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Destination/destination.css
  src/pages/Destination/destination.jsx
  src/pages/booking/Booking.jsx
  src/pages/booking/booking.css
  src/pages/home/home.jsx
Labels: Work in progress

#12 #185285073 admin dashboard to control all the activities
  package-lock.json
  src/App.css
  src/App.jsx
  src/component/routes/index.jsx
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/component/trial.jsx
  src/constants/admindrivers.jsx
  src/constants/busmanage.jsx
  src/constants/claims.jsx
  src/constants/index.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash3.jsx
  src/pages/Admindashboard/admindash4.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/image/gggggggg.JPG
Labels: Ready to merge

#10 Ft faby
  package-lock.json
  package.json
  src/App.css
  src/component/routes/index.jsx
  src/main.jsx
  src/pages/login.css
  src/pages/login.jsx
  src/pages/signup.css
  src/pages/signup.jsx
Labels: Ready to merge

#16 fixed development one
  src/component/routes/index.jsx
Labels: Ready to merge

#17 fixed deployment two
  src/pages/Destination/destination.jsx
Labels: Ready to merge

#18 fixed deployment three
  src/pages/home/home.jsx
  src/pages/login.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#19 Ft login fix 2
  public/index.html
  src/component/routes/index.jsx
  src/constants/trackingc.jsx
  src/pages/Tracking/tracking.css
  src/pages/Tracking/tracking.js
  src/pages/Tracking/tracking.jsx
  src/pages/login.css
  src/pages/login.jsx
Labels: Ready to merge

#20 renamed the classes
  src/pages/signup.css
  src/pages/signup.jsx
Labels: Ready to merge

#21 fixed deployment three
  src/component/routes/index.jsx
  src/pages/navigation/NavigationBar.css
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#23 fixing deployment on homepage
  src/App.css
  src/component/routes/index.jsx
  src/pages/Destination/destination.css
  src/pages/booking/booking.css
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/navigation/NavigationBar.css
Labels: Ready to merge

#24 Ft driver dashboard
  src/App.css
  src/App.jsx
  src/pages/booking/Booking.jsx
  src/pages/booking/booking.css
Labels: Ready to merge

#11 Ft footer
  package-lock.json
  src/App.jsx
  src/component/footer.css
  src/component/navbar.css
  src/component/navbar.jsx
  src/component/newfooter.jsx
  src/component/oldfooter.jsx
  src/index.css
Labels: bug

#31 fixing admin dashboard css styles
  package-lock.json
  src/App.jsx
  src/Destination.jsx
  src/Driver.jsx
  src/component/routes/index.jsx
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash3.jsx
  src/pages/Admindashboard/admindash4.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/booking/Booking.jsx
  src/pages/home/home.jsx
Labels: Ready to merge

#32 fixing deployment
  src/App.jsx
  src/pages/booking/Booking.jsx
Labels: Ready to merge

#33 fixing new errors
  src/App.jsx
  src/component/routes/index.jsx
  src/pages/home/home.jsx
Labels: Ready to merge

#35 fixing errors
  package-lock.json
  src/pages/home/trial.css
  src/pages/home/trial.jsx
Labels: Ready to merge

#9 Contact us page
  package-lock.json
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/Navigation/Navigation.css
  src/pages/Navigation/Navigation.jsx
  src/pages/contact-us/GoogleMap.css
  src/pages/contact-us/GoogleMap.jsx
  src/pages/contact-us/contactUs.css
  src/pages/contact-us/contactUs.jsx
  src/pages/image/Desktop - 1 (1).png
  src/pages/image/Logo.png
  src/pages/image/background1.png
Labels: bug

#30 Ft booking
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/index.css
  src/main.jsx
  src/pages/Booking/BookingForm.css
  src/pages/Booking/BookingForm.jsx
Labels: Ready to merge

#36 fix three
  src/component/Side/driveSidebar.css
  src/component/Side/driveSidebar.jsx
  src/pages/Destination/destination.css
  src/pages/booking/Booking.jsx
  src/pages/booking/booking.css
Labels: Ready to merge

#37 adding new features on form section
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Admindashboard/admindash5.jsx
Labels: Ready to merge

#38 homepage
  package-lock.json
  src/component/footer.css
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/navigation/NavigationBar.css
Labels: Ready to merge

#40 login fix
  src/component/routes/index.jsx
  src/pages/login-signup/log-in.css
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.css
  src/pages/login-signup/sign-up.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#42 fixing deployment
  src/component/footer.css
  src/component/routes/index.jsx
  src/pages/home/home.css
Labels: Ready to merge

#44 deployment fix
  src/pages/contact-us/GoogleMap.jsx
  src/pages/contact-us/contactUs.css
  src/pages/contact-us/contactUs.jsx
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.jsx
Labels: Ready to merge

#45 deployment fix
  src/component/routes/index.jsx
Labels: Ready to merge

#46 fixing deployment
  src/component/routes/index.jsx
Labels: Ready to merge

#47 fixing pages
  package-lock.json
  package.json
  src/component/newfooter.jsx
  src/component/routes/index.jsx
  src/pages/contact-us/contactUs.css
  src/pages/home/home.jsx
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#48 fixing bookingform
  src/component/routes/index.jsx
  src/pages/home/home.css
  src/pages/home/home.jsx
Labels: Ready to merge

#49 new fix
  src/component/routes/index.jsx
Labels: Ready to merge

#50 fix three
  package-lock.json
  src/component/Side/driveSidebar.css
  src/component/Side/driveSidebar.jsx
  src/pages/Destination/destination.css
  src/pages/Destination/destination.jsx
  src/pages/booking/Booking.jsx
  src/pages/booking/booking.css
Labels: Ready to merge

#52 NEw changes on admin dashboard
  src/component/routes/index.jsx
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash3.jsx
  src/pages/Admindashboard/admindash4.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/Booking/BookingForm.css
  src/pages/booking/Booking.jsx
  src/pages/contact-us/contactUs.css
Labels: Ready to merge

#51 Ft-cancelTicket page
  package-lock.json
  src/App.jsx
  src/component/routes/index.jsx
  src/pages/Booking/BookingForm.jsx
  src/pages/cancel-ticket/cancelTicket.css
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/contact-us/contactUs.css
  src/pages/contact-us/contactUs.jsx
Labels: Ready to merge

#53 fixing homepage
  src/component/routes/index.jsx
  src/pages/contact-us/contactUs.css
  src/pages/home/home.css
  src/pages/login-signup/log-in.css
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.css
  src/pages/login-signup/sign-up.jsx
Labels: Ready to merge

#54 fixing deployment
  src/component/routes/index.jsx
  src/pages/Navigation/Navigation.css
  src/pages/Navigation/Navigation.jsx
  src/pages/cancel-ticket/cancelTicket.css
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/contact-us/contactUs.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#55 fixing deployment
  src/component/routes/index.jsx
  src/pages/home/home.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#56 fixing responsiveness
  src/component/footer.css
  src/component/navbar.css
  src/component/navbar.jsx
  src/component/newfooter.jsx
  src/component/oldfooter.jsx
  src/pages/Booking/BookingForm.css
  src/pages/Booking/BookingForm.jsx
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/home/images.jsx
Labels: Ready to merge

#57 fixing deployment
  src/component/footer.css
  src/component/newfooter.jsx
  src/component/routes/index.jsx
  src/pages/cancel-ticket/cancelTicket.css
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/home/home.css
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#58 fixing deployment
  src/pages/Tracking/tracking.css
Labels: Ready to merge

#60 fixing booking page
  package-lock.json
  src/component/routes/index.jsx
  src/pages/Booking/BookingForm.jsx
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/newBooking/Seat.css
  src/pages/newBooking/Seat.jsx
  src/pages/newBooking/newBookingForm.css
  src/pages/newBooking/newBookingForm.jsx
Labels: Ready to merge

#62 Ft contactintegration
  package-lock.json
  src/pages/contact-us/contactUs.jsx
Labels: Ready to merge

#61 fixing deployment
  src/component/routes/index.jsx
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/navigation/NavigationBar.jsx
  src/pages/newBooking/Seat.css
  src/pages/newBooking/newBookingForm.css
Labels: Ready to merge

#64 fixing deployment
  src/component/routes/index.jsx
Labels: Ready to merge

#65 change local link
  src/pages/contact-us/contactUs.jsx
Labels: Ready to merge

#66 login in according to user role
  package-lock.json
  package.json
  src/component/routes/index.jsx
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.jsx
Labels: Ready to merge

#67 change local link
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#68 update user endpoint
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#69 fixing cancel ticket-page
  src/component/newfooter.jsx
  src/component/routes/index.jsx
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/home/home.css
  src/pages/login-signup/log-in.css
  src/pages/login-signup/log-in.jsx
  src/pages/login-signup/sign-up.css
  src/pages/login-signup/sign-up.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#70 Ft booking integration
  src/pages/newBooking/newBookingForm.jsx
Labels: Ready to merge

#72 fixing deployment
  src/component/routes/index.jsx
Labels: Ready to merge

#73 Ft dash board driver
  src/component/Side/driveSidebar.jsx
  src/component/routes/index.jsx
  src/pages/Destination/destination.jsx
  src/pages/Driverdashboard/driverdashboard.css
  src/pages/Driverdashboard/driverdashboard.jsx
  src/pages/booking/Booking.jsx
  src/pages/image/Screenshot 2023-06-22 011226.png
  src/pages/image/chart.png
  src/pages/image/chartii.png
Labels: Ready to merge

#75 get messeges
  src/pages/Admindashboard/admindash6.jsx
Labels: Ready to merge

#77 get messeges
  src/pages/Admindashboard/admindash5.jsx
Labels: Ready to merge

#78 fixing cancel ticket page
  package-lock.json
  package.json
  src/component/routes/index.jsx
  src/pages/NewCancelTicket/newCancelTicket.css
  src/pages/NewCancelTicket/newCancelTicket.jsx
Labels: Ready to merge

#80 adding functionality to some buttons
  src/App.css
  src/component/sidebar.css
  src/constants/index.css
  src/index.css
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/Booking/BookingForm.css
  src/pages/booking/booking.css
  src/pages/contact-us/contactUs.css
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#79 Ft driverdash integration
  src/pages/booking/Booking.jsx
Labels: Ready to merge

#81 fixing deployment
  src/component/routes/index.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/Tracking/tracking.jsx
  src/pages/cancel-ticket/cancelTicket.css
  src/pages/cancel-ticket/cancelTicket.jsx
  src/pages/newBooking/newBookingForm.css
  src/pages/newBooking/newBookingForm.jsx
Labels: Ready to merge

#82 fixing deployment
  src/component/routes/index.jsx
Labels: Ready to merge

#83 fixing pages
  package-lock.json
  src/component/routes/index.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/NewCancelTicket/newCancelTicket.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#84 Fixing deploy2
  src/component/sidebar.jsx
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#87 fix login
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#88 fixing pages
  src/component/footer.css
  src/component/newfooter.jsx
  src/pages/newBooking/newBookingForm.jsx
Labels: Ready to merge

#89 Ft newadmin// fixing fetching
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
Labels: Ready to merge

#91 Fixing missing pages
  h --set-upstream origin ft-adminrealrespo
  src/component/sidebar.css
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash5.jsx
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#90 Fixing footer
  src/pages/aboutus/aboutus.jsx
Labels: Ready to merge

#92 update tost
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#93 fixing about-us
  src/component/footer.css
  src/pages/aboutus/aboutus.css
  src/pages/aboutus/aboutus.jsx
  src/pages/navigation/NavigationBar.jsx
Labels: Ready to merge

#99 we have added API.js to add BASE-URL
  src/Api.js
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge

#104 fixing form
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
Labels: Ready to merge

#103 fixing form page
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash2.jsx
  src/pages/Admindashboard/admindash5.jsx
Labels: Ready to merge

#98 fixing-homepage
  src/assets/ticketsrm.png
  src/component/footer.css
  src/fonts/OFL.txt
  src/fonts/Poppins-Black.ttf
  src/fonts/Poppins-BlackItalic.ttf
  src/fonts/Poppins-Bold.ttf
  src/fonts/Poppins-BoldItalic.ttf
  src/fonts/Poppins-ExtraBold.ttf
  src/fonts/Poppins-ExtraBoldItalic.ttf
  src/fonts/Poppins-ExtraLight.ttf
  src/fonts/Poppins-ExtraLightItalic.ttf
  src/fonts/Poppins-Italic.ttf
  src/fonts/Poppins-Light.ttf
  src/fonts/Poppins-LightItalic.ttf
  src/fonts/Poppins-Medium.ttf
  src/fonts/Poppins-MediumItalic.ttf
  src/fonts/Poppins-Regular.ttf
  src/fonts/Poppins-SemiBold.ttf
  src/fonts/Poppins-SemiBoldItalic.ttf
  src/fonts/Poppins-Thin.ttf
  src/fonts/Poppins-ThinItalic.ttf
  src/pages/Admindashboard/admin.css
  src/pages/home/home.css
  src/pages/home/home.jsx
  src/pages/image/ticket1.png
Labels: Ready to merge

#105 Viewing all messages sent
  index.html
  src/App.jsx
  src/component/routes/index.jsx
  src/component/sidebar.jsx
  src/pages/Admindashboard/admindash6.jsx
Labels: Ready to merge

#106 fix booking
  src/Driver.jsx
  src/component/Side/driveSidebar.jsx
  src/pages/Destination/destination.css
  src/pages/Destination/destination.jsx
Labels: Ready to merge

#107 fixing form page
  src/component/sidebar.jsx
  src/pages/Admindashboard/admin.css
  src/pages/Admindashboard/admindash2.jsx
Labels: Ready to merge

#108 Ft trackingfix
  package-lock.json
  src/pages/Tracking/tracking.css
  src/pages/Tracking/tracking.jsx
  src/pages/login-signup/log-in.jsx
Labels: Ready to merge
